### ISSUE TITLE
No "error" key?

### ISSUE THREAD

**Issue by malhal** [mlanin/laravel-api-exceptions#1]
Why is the error key "id" and not "error"? Just wondering thanks.

**Comment by mlanin** [comment]
Because for me "error" it too vague. It can contain everything. Message, ID, any nested information... That's why I chose "id" to reduce this uncertainty :)

Also in my projects I'm trying to follow [JSON API](http://jsonapi.org) specification. And there is "id" too http://jsonapi.org/format/#errors

**Comment by malhal** [comment]
That spec requires an 'errors' key at the top level, which solves the problem of differentiating between a valid record's id and an error case.

_"Error objects MUST be returned as an array keyed by errors in the top level of a JSON API document."_

**Comment by mlanin** [comment]
Oh, that's what you mean. I know that at this point my implementation differs from the spec but I think there is no need to wrap content into additional 'error' attribute, since you already know that there is an error. HTTP status is pretty obvious and should rise an exception.

Also I never encountered the situation where it was hard to differentiate error from the valid answer, since successful answer is always wrapped in 'data' or 'pages' or any other attribute.

But I know that it is a valid point. May be I'll change this behaviour later.

**Comment by karneaud** [comment]
@mlanin @malhal  I am having a very similar concern with the validation errors format with the "errors" being in the "meta" and not at the top level....can we override this?

**Comment by mlanin** [comment]
@karneaud `ValidationFailedApiException` has an additional method `getNativeErrors` that will return validation errors in it's native Laravel way.

You can make your own implementation of `ValidationFailedApiException` by extending it and using this method while overriding its `toArray` method. Then go to you abstract Request class and override `protected function failedValidation(Validator $validator)` method to throw your exception.

I understand that it's not the best solution, but it is everything I can advise you by now.

I'll think about templating the answer so that anyone can change the answer structure.

**Comment by mlanin** [comment]
Guys, sorry for the delay. I implemented an ability to override default output. So if you still need it, just look in the readme.
